import { AnalysisOptions } from "./types";

export const DEFAULT_OPTIONS: AnalysisOptions = {
  beginnerFriendly: true,
  showVowelHarmony: true,
  showIPA: false,
  outputLanguage: "English",
  detailLevel: "Normal",
};

export const EXAMPLE_INPUTS = [
  "Evlerimizden",
  "Bugün okula gitmeyeceğim.",
  "Avrupalılaştıramadıklarımızdanmışsınızcasına",
  "Seni seviyorum.",
  "Gelebilirim",
  "Kitabı masaya bıraktı.",
];

export const POS_COLORS: Record<string, string> = {
  NOUN: "bg-blue-100 text-blue-800 border-blue-200",
  VERB: "bg-green-100 text-green-800 border-green-200",
  ADJ: "bg-purple-100 text-purple-800 border-purple-200",
  ADV: "bg-yellow-100 text-yellow-800 border-yellow-200",
  PRON: "bg-orange-100 text-orange-800 border-orange-200",
  DET: "bg-gray-100 text-gray-800 border-gray-200",
  ADP: "bg-indigo-100 text-indigo-800 border-indigo-200",
  CONJ: "bg-pink-100 text-pink-800 border-pink-200",
  PART: "bg-teal-100 text-teal-800 border-teal-200",
  INTJ: "bg-red-100 text-red-800 border-red-200",
  NUM: "bg-cyan-100 text-cyan-800 border-cyan-200",
  PUNCT: "bg-slate-100 text-slate-800 border-slate-200",
  X: "bg-gray-100 text-gray-600 border-gray-200",
};

export const UI_STRINGS = {
  en: {
    appTitle: "TurkLingo",
    tagline: "AI Grammar & Morphology Analyzer",
    about: "About",
    analyze: "Analyze",
    analyzing: "Analyzing...",
    clear: "Clear",
    options: "Options",
    hideOptions: "Hide Options",
    inputPlaceholder: "e.g., Evlerimizden...",
    inputLabel: "Enter Turkish word or sentence",
    // Tabs
    mainTabs: {
      analyzer: "Analyzer",
      constructor: "Constructor",
      reference: "Grammar Library",
    },
    constructor: {
      title: "Word Constructor",
      posLabel: "Part of Speech",
      rootLabel: "Root",
      rootHint: "Pick a root to start building.",
      suffixesLabel: "Suffixes",
      clear: "Clear",
      analyze: "Analyze",
      copy: "Copy",
      orderHint:
        "Order enforced: plural → possessive → cases (nouns), tense → person (verbs). One selection per category.",
      contractionHint:
        "Contractions: vowel-final + -Iyor drops the last vowel (oku + iyor → okuyor); aorist -Ar loses its vowel after vowel-final stems (oku + ar → okur).",
      preview: "Preview",
      meaning: "Didactic meaning",
      chain: "Morphology chain",
      appliedRules: "Applied rules",
      rules: {
        vowelHarmony: "Vowel harmony",
        bufferConsonant: "Buffer consonant",
        consonantSoftening: "Consonant softening",
        consonantAssimilation: "Consonant assimilation",
      },
      emptyMeaning: "Run analysis to see a didactic meaning.",
      emptyPreview: "Select a root to begin.",
      categories: {
        plural: "Plural",
        possessive: "Possessive",
        cases: "Cases",
        tenses: "Tense/Aspect",
        person: "Person",
        derivation: "Derivation",
      },
      posOptions: {
        NOUN: "Noun",
        VERB: "Verb",
        ADJ: "Adjective",
      },
    },
    // Options
    beginnerFriendly: "Beginner-friendly explanations",
    showVowelHarmony: "Show vowel harmony rules",
    showIPA: "Show IPA pronunciation",
    detailLevel: "Detail Level",
    outputLanguage: "Output Language",
    // Results
    detectedLanguage: "Detected Language",
    turkishLanguage: "Turkish 🇹🇷",
    sentence: "Sentence",
    singleWord: "Single Word",
    unknown: "Unknown",
    meaning: "Meaning",
    emptyPlaceholder: "—",
    keyNotes: "Key Grammatical Notes",
    commonMistakes: "Common Mistakes",
    rulesAndNotes: "Rules & Notes",
    morphologyChain: "Morphology Chain",
    inflection: "Inflection",
    derivation: "Derivation",
    root: "Root",
    lemmaLabel: "Lemma",
    harmonyRules: "Harmony Rules Applied",
    tabs: {
      overview: "Overview",
      tokens: "Tokens",
      suffix: "Suffixes",
      reference: "Reference",
    },
    detailLevelOptions: {
      Brief: "Brief",
      Normal: "Normal",
      Deep: "Deep",
    },
    outputLanguageOptions: {
      English: "English",
      Turkish: "Turkish",
      Russian: "Russian",
    },
    posTags: {
      NOUN: "Noun",
      VERB: "Verb",
      ADJ: "Adjective",
      ADV: "Adverb",
      PRON: "Pronoun",
      DET: "Determiner",
      ADP: "Adposition",
      CONJ: "Conjunction",
      PART: "Particle",
      INTJ: "Interjection",
      NUM: "Numeral",
      PUNCT: "Punctuation",
      X: "Other",
    },
    grammaticalTerms: {
      // Keys/Categories
      number: "number",
      person: "person",
      case: "case",
      possessive: "possessive",
      tense: "tense",
      aspect: "aspect",
      mood: "mood",
      voice: "voice",
      polarity: "polarity",
      evidentiality: "evidentiality",
      // Values
      plural: "plural",
      singular: "singular",
      ablative: "ablative",
      accusative: "accusative",
      dative: "dative",
      locative: "locative",
      genitive: "genitive",
      nominative: "nominative",
    },
    ref: {
      nouns: "Noun Inflections",
      verbs: "Verb Conjugations",
      derivations: "Common Derivations",
      phonetics: "Phonetic Rules",
      vowelHarmony: "Vowel Harmony",
      vowelDrop: "Vowel Drop / Contraction",
      consonantAlteration: "Consonant Softening (KETÇAP)",
      consonantAssimilation: "Consonant Assimilation (Fıstıkçı Şahap)",
      bufferLetters: "Buffer Letters (YaŞaSıN)",
      suffix: "Suffix",
      meaning: "Function / Meaning",
      example: "Example",
      trigger: "Last Vowel",
      result: "Suffix Vowel",
      change: "Change",
      cases: "Case",
      plural: "Plural",
      possessive: "Possession",
      tenses: "Tense/Aspect",
      person: "Person",
      derivation: "Derivation",
      letter: "Letter",
    },
    history: "Recent Analyses",
    copyJson: "JSON",
    copyJsonSuccess: "JSON copied to clipboard!",
    tryAgain: "Try Again",
    analysisFailed: "Analysis Failed",
    errors: {
      missingApiKey: "Missing API key. Set API_KEY and reload.",
      generic: "An unexpected error occurred. Please try again.",
    },
    footer: "© {year} TurkLingo Analyzer. Built with React, Tailwind & Gemini.",
    aboutMessage: "TurkLingo v1.0\nPowered by Google Gemini",
  },
  ru: {
    appTitle: "TurkLingo",
    tagline: "ИИ Анализатор грамматики",
    about: "О приложении",
    analyze: "Анализ",
    analyzing: "Думаю...",
    clear: "Очистить",
    options: "Настройки",
    hideOptions: "Скрыть настройки",
    inputPlaceholder: "например, Evlerimizden...",
    inputLabel: "Введите турецкое слово или фразу",
    // Tabs
    mainTabs: {
      analyzer: "Анализатор",
      constructor: "Конструктор",
      reference: "Справочник",
    },
    constructor: {
      title: "Конструктор слов",
      posLabel: "Часть речи",
      rootLabel: "Корень",
      rootHint: "Выберите корень, чтобы начать.",
      suffixesLabel: "Суффиксы",
      clear: "Сбросить",
      analyze: "Анализ",
      copy: "Копировать",
      orderHint:
        "Порядок фиксирован: мн. число → притяжательность → падеж (сущ.), время → лицо (глаг.). Один выбор на категорию.",
      contractionHint:
        "Сжатия: основа на гласную + -Iyor теряет последнюю гласную (oku + iyor → okuyor); аорист -Ar теряет гласную после основы на гласную (oku + ar → okur).",
      preview: "Предпросмотр",
      meaning: "Объясняющее значение",
      chain: "Морфологическая цепочка",
      appliedRules: "Примененные правила",
      rules: {
        vowelHarmony: "Гармония гласных",
        bufferConsonant: "Промежуточная согласная",
        consonantSoftening: "Смягчение согласных",
        consonantAssimilation: "Уподобление согласных",
      },
      emptyMeaning: "Запустите анализ, чтобы увидеть объясняющее значение.",
      emptyPreview: "Выберите корень, чтобы начать.",
      categories: {
        plural: "Мн. число",
        possessive: "Притяжательность",
        cases: "Падежи",
        tenses: "Время/Аспект",
        person: "Лицо",
        derivation: "Словообразование",
      },
      posOptions: {
        NOUN: "Сущ.",
        VERB: "Глаг.",
        ADJ: "Прил.",
      },
    },
    // Options
    beginnerFriendly: "Простые объяснения (для новичков)",
    showVowelHarmony: "Правила гармонии гласных",
    showIPA: "Показывать транскрипцию (IPA)",
    detailLevel: "Детализация",
    outputLanguage: "Язык ответа",
    // Results
    detectedLanguage: "Определенный язык",
    turkishLanguage: "Турецкий 🇹🇷",
    sentence: "Предложение",
    singleWord: "Слово",
    unknown: "Неизвестно",
    meaning: "Значение",
    emptyPlaceholder: "—",
    keyNotes: "Грамматические заметки",
    commonMistakes: "Частые ошибки",
    rulesAndNotes: "Правила и заметки",
    morphologyChain: "Морфологическая цепочка",
    inflection: "Словоизменение",
    derivation: "Словообразование",
    root: "Корень",
    lemmaLabel: "Лемма",
    harmonyRules: "Гармония гласных",
    tabs: {
      overview: "Обзор",
      tokens: "Токены",
      suffix: "Суффиксы",
      reference: "Справочник",
    },
    detailLevelOptions: {
      Brief: "Кратко",
      Normal: "Нормально",
      Deep: "Подробно",
    },
    outputLanguageOptions: {
      English: "Английский",
      Turkish: "Турецкий",
      Russian: "Русский",
    },
    posTags: {
      NOUN: "Сущ.",
      VERB: "Глагол",
      ADJ: "Прил.",
      ADV: "Наречие",
      PRON: "Местоим.",
      DET: "Детерм.",
      ADP: "Послелог",
      CONJ: "Союз",
      PART: "Частица",
      INTJ: "Междом.",
      NUM: "Числ.",
      PUNCT: "Пунктуация",
      X: "Прочее",
    },
    grammaticalTerms: {
      // Keys/Categories
      number: "число",
      person: "лицо",
      case: "падеж",
      possessive: "притяжательность",
      tense: "время",
      aspect: "аспект",
      mood: "наклонение",
      voice: "залог",
      polarity: "отрицание",
      evidentiality: "очевидность",
      // Values
      plural: "мн. число",
      singular: "ед. число",
      ablative: "исходный",
      accusative: "винительный",
      dative: "дательный",
      locative: "местный",
      genitive: "родительный",
      nominative: "именительный",
    },
    ref: {
      nouns: "Изменение существительных",
      verbs: "Спряжение глаголов",
      derivations: "Словообразование",
      phonetics: "Фонетические правила",
      vowelHarmony: "Гармония гласных",
      vowelDrop: "Выпадение/сжатие гласной",
      consonantAlteration: "Смягчение согласных (KETÇAP)",
      consonantAssimilation: "Уподобление согласных (Fıstıkçı Şahap)",
      bufferLetters: "Промежуточные буквы (YaŞaSıN)",
      suffix: "Суффикс",
      meaning: "Функция / Значение",
      example: "Пример",
      trigger: "Последняя гласная",
      result: "Гласная суффикса",
      change: "Замена",
      cases: "Падеж",
      plural: "Мн. число",
      possessive: "Принадлежность",
      tenses: "Время/Аспект",
      person: "Лицо",
      derivation: "Образование",
      letter: "Буква",
    },
    history: "История",
    copyJson: "JSON",
    copyJsonSuccess: "JSON скопирован в буфер обмена!",
    tryAgain: "Повторить",
    analysisFailed: "Ошибка анализа",
    errors: {
      missingApiKey: "Отсутствует API ключ. Укажите API_KEY и перезагрузите.",
      generic: "Произошла ошибка. Пожалуйста, попробуйте еще раз.",
    },
    footer: "© {year} TurkLingo Analyzer. Создано на React, Tailwind и Gemini.",
    aboutMessage: "TurkLingo v1.0\nРаботает на Google Gemini",
  },
};

export const PHONETIC_RULES = {
  en: {
    vowelTwoWay: [
      { trigger: "a, ı, o, u", result: "a", examples: "-lar, -da, -dan, -a" },
      { trigger: "e, i, ö, ü", result: "e", examples: "-ler, -de, -den, -e" },
    ],
    vowelFourWay: [
      { trigger: "a, ı", result: "ı", examples: "-ın, -lı, -dı, -cı" },
      { trigger: "e, i", result: "i", examples: "-in, -li, -di, -ci" },
      { trigger: "o, u", result: "u", examples: "-un, -lu, -du, -cu" },
      { trigger: "ö, ü", result: "ü", examples: "-ün, -lü, -dü, -cü" },
    ],
    consonantsSoftening: [
      {
        change: "k → ğ / g",
        context: "Becomes ğ (or g) before a vowel",
        example: "Köpek + i = Köpeği",
      },
      {
        change: "t → d",
        context: "Becomes d before a vowel",
        example: "Git + iyor = Gidiyor",
      },
      {
        change: "ç → c",
        context: "Becomes c before a vowel",
        example: "Ağaç + a = Ağaca",
      },
      {
        change: "p → b",
        context: "Becomes b before a vowel",
        example: "Kitap + ı = Kitabı",
      },
    ],
    consonantsAssimilation: [
      {
        change: "c → ç",
        context: "After voiceless (f, s, t, k, ç, ş, h, p)",
        example: "Aş + cı = Aşçı",
      },
      {
        change: "d → t",
        context: "After voiceless (f, s, t, k, ç, ş, h, p)",
        example: "Kitap + da = Kitapta",
      },
      {
        change: "g → k",
        context: "After voiceless (f, s, t, k, ç, ş, h, p)",
        example: "Sert + ce = Sertçe",
      },
    ],
    bufferLetters: [
      {
        letter: "y",
        context: "General buffer between two vowels",
        example: "Kedi + e = Kediye",
      },
      {
        letter: "ş",
        context: "Distributive numbers only",
        example: "İki + er = İkişer",
      },
      {
        letter: "s",
        context: "3rd person possessive suffix",
        example: "Kedi + i = Kedisi",
      },
      {
        letter: "n",
        context: "Genitive case, or between possessive and cases",
        example: "Kedi + in = Kedinin, Arabası + nı = Arabasını",
      },
    ],
    vowelDrop: [
      {
        change: "V → ∅",
        context: "Final vowel drops before -Iyor",
        example: "oku + iyor = okuyor, bekle + iyor = bekliyor",
      },
      {
        change: "Ar → r",
        context: "Aorist loses its vowel after a vowel-final stem",
        example: "oku + ar = okur, ara + ar = arar",
      },
    ],
  },
  ru: {
    vowelTwoWay: [
      { trigger: "a, ı, o, u", result: "a", examples: "-lar, -da, -dan, -a" },
      { trigger: "e, i, ö, ü", result: "e", examples: "-ler, -de, -den, -e" },
    ],
    vowelFourWay: [
      { trigger: "a, ı", result: "ı", examples: "-ın, -lı, -dı, -cı" },
      { trigger: "e, i", result: "i", examples: "-in, -li, -di, -ci" },
      { trigger: "o, u", result: "u", examples: "-un, -lu, -du, -cu" },
      { trigger: "ö, ü", result: "ü", examples: "-ün, -lü, -dü, -cü" },
    ],
    consonantsSoftening: [
      {
        change: "k → ğ / g",
        context: "Переходит в ğ (или g) перед гласной",
        example: "Köpek + i = Köpeği",
      },
      {
        change: "t → d",
        context: "Переходит в d перед гласной",
        example: "Git + iyor = Gidiyor",
      },
      {
        change: "ç → c",
        context: "Переходит в c перед гласной",
        example: "Ağaç + a = Ağaca",
      },
      {
        change: "p → b",
        context: "Переходит в b перед гласной",
        example: "Kitap + ı = Kitabı",
      },
    ],
    consonantsAssimilation: [
      {
        change: "c → ç",
        context: "После глухих (f, s, t, k, ç, ş, h, p)",
        example: "Aş + cı = Aşçı",
      },
      {
        change: "d → t",
        context: "После глухих (f, s, t, k, ç, ş, h, p)",
        example: "Kitap + da = Kitapta",
      },
      {
        change: "g → k",
        context: "После глухих (f, s, t, k, ç, ş, h, p)",
        example: "Sert + ce = Sertçe",
      },
    ],
    bufferLetters: [
      {
        letter: "y",
        context: "Общий разделитель между двумя гласными",
        example: "Kedi + e = Kediye",
      },
      {
        letter: "ş",
        context: "Только в разделительных числительных",
        example: "İki + er = Икишер",
      },
      {
        letter: "s",
        context: "В суффиксе принадлежности 3-го лица",
        example: "Kedi + i = Kedisi",
      },
      {
        letter: "n",
        context: "Родительный падеж или между притяжательностью и падежом",
        example: "Kedi + in = Kedinin, Arabası + nı = Arabasını",
      },
    ],
    vowelDrop: [
      {
        change: "V → ∅",
        context: "Конечная гласная выпадает перед -Iyor",
        example: "oku + iyor = okuyor, bekle + iyor = bekliyor",
      },
      {
        change: "Ar → r",
        context: "Аорист теряет гласную после основы на гласную",
        example: "oku + ar = okur, ara + ar = arar",
      },
    ],
  },
};

export const SUFFIX_DATA = {
  en: {
    nouns: [
      { cat: "plural", s: "-lar / -ler", m: "Plural", e: "Evler (Houses)" },
      {
        cat: "cases",
        s: "-(y)i / -ı / -u / -ü",
        m: "Accusative (Specific Direct Object)",
        e: "Evi gördüm (I saw the house)",
      },
      {
        cat: "cases",
        s: "-(y)e / -a",
        m: "Dative (Directional: To / Towards)",
        e: "Eve gidiyorum (I'm going home)",
      },
      {
        cat: "cases",
        s: "-de / -da / -te / -ta",
        m: "Locative (Position: At / In / On)",
        e: "Evde (At home)",
      },
      {
        cat: "cases",
        s: "-den / -dan / -ten / -tan",
        m: "Ablative (Origin: From / Than)",
        e: "Evden (From house)",
      },
      {
        cat: "cases",
        s: "-(n)in / -ın / -un / -ün",
        m: "Genitive (Possessor: 's / Of)",
        e: "Evin kapısı (The door of the house)",
      },
      {
        cat: "possessive",
        s: "-(i)m / -ım",
        m: "My (1st Person Sing.)",
        e: "Evim (My house)",
      },
      {
        cat: "possessive",
        s: "-(i)n / -ın",
        m: "Your (2nd Person Sing.)",
        e: "Evin (Your house)",
      },
      {
        cat: "possessive",
        s: "-(s)i / -ı",
        m: "His/Her/Its (3rd Person Sing.)",
        e: "Evi (His/Her house)",
      },
      {
        cat: "possessive",
        s: "-(i)miz / -ımız / -umuz / -ümüz",
        m: "Our (1st Person Plur.)",
        e: "Evimiz (Our house)",
      },
      {
        cat: "possessive",
        s: "-(i)niz / -ınız / -unuz / -ünüz",
        m: "Your (2nd Person Plur.)",
        e: "Eviniz (Your house)",
      },
      {
        cat: "possessive",
        s: "-leri / -ları",
        m: "Their (3rd Person Plur.)",
        e: "Evleri (Their house)",
      },
    ],
    verbs: [
      {
        cat: "tenses",
        s: "-ıyor / -iyor / -uyor / -üyor",
        m: "Present Continuous (-ing)",
        e: "Geliyorum (I am coming), Bakıyor (Looking)",
      },
      {
        cat: "tenses",
        s: "-di / -dı / -du / -dü",
        m: "Past (Seen/Witnessed)",
        e: "Geldi (He/She came)",
      },
      {
        cat: "tenses",
        s: "-miş / -mış / -muş / -müş",
        m: "Past (Reported/Heard)",
        e: "Gelmiş (He reportedly came)",
      },
      {
        cat: "tenses",
        s: "-ecek / -acak",
        m: "Future (Will)",
        e: "Gelecek (He/She will come)",
      },
      {
        cat: "tenses",
        s: "-r / -er / -ar",
        m: "Aorist (General / Often / Polite)",
        e: "Gelir (He/She usually comes)",
      },
      {
        cat: "person",
        s: "-im / -ım",
        m: "Personal marker: I",
        e: "Yazıyorum (I am writing)",
      },
      {
        cat: "person",
        s: "-sin / -sın",
        m: "Personal marker: You",
        e: "Yazıyorsun (You are writing)",
      },
      {
        cat: "person",
        s: "ø",
        m: "Personal marker: He/She/It",
        e: "Yazıyor (He is writing)",
      },
    ],
    derivations: [
      {
        cat: "derivation",
        s: "-ci / -cı / -cü / -cu",
        m: "Occupation / Habitual doer",
        e: "Sütçü (Milkman)",
      },
      {
        cat: "derivation",
        s: "-lik / -lık / -lük / -luk",
        m: "Abstraction / Destination",
        e: "Güzellik (Beauty), Kitaplık (Library)",
      },
      {
        cat: "derivation",
        s: "-li / -lı / -lü / -lu",
        m: "With / Possessing property",
        e: "Şekerli (With sugar)",
      },
      {
        cat: "derivation",
        s: "-siz / -sız / -süz / -suz",
        m: "Without / Lacking",
        e: "Şekersiz (Without sugar)",
      },
    ],
  },
  ru: {
    nouns: [
      {
        cat: "plural",
        s: "-lar / -ler",
        m: "Множественное число",
        e: "Evler (Дома)",
      },
      {
        cat: "cases",
        s: "-(y)i / -ı / -u / -ü",
        m: "Винительный падеж (Опред. объект)",
        e: "Evi gördüm (Я видел дом)",
      },
      {
        cat: "cases",
        s: "-(y)e / -a",
        m: "Дательный падеж (Направление)",
        e: "Eve gidiyorum (Я иду домой)",
      },
      {
        cat: "cases",
        s: "-de / -da / -te / -ta",
        m: "Местный падеж (Местоположение)",
        e: "Evde (Дома)",
      },
      {
        cat: "cases",
        s: "-den / -dan / -ten / -tan",
        m: "Исходный падеж (Откуда / Чем)",
        e: "Evden (Из дома)",
      },
      {
        cat: "cases",
        s: "-(n)in / -ın / -un / -ün",
        m: "Родительный падеж (Обладание)",
        e: "Evin kapısı (Дверь дома)",
      },
      {
        cat: "possessive",
        s: "-(i)m / -ım",
        m: "Мой (1-е л. ед.ч.)",
        e: "Evim (Мой дом)",
      },
      {
        cat: "possessive",
        s: "-(i)n / -ın",
        m: "Твой (2-е л. ед.ч.)",
        e: "Evin (Твой дом)",
      },
      {
        cat: "possessive",
        s: "-(s)i / -ı",
        m: "Его/Её (3-е л. ед.ч.)",
        e: "Evi (Его дом)",
      },
      {
        cat: "possessive",
        s: "-(i)miz / -ımız / -umuz / -ümüz",
        m: "Наш (1-е л. мн.ч.)",
        e: "Evimiz (Наш дом)",
      },
      {
        cat: "possessive",
        s: "-(i)niz / -ınız / -unuz / -ünüz",
        m: "Ваш (2-е л. мн.ч.)",
        e: "Eviniz (Ваш дом)",
      },
      {
        cat: "possessive",
        s: "-leri / -ları",
        m: "Их (3-е л. мн.ч.)",
        e: "Evleri (Их дом)",
      },
    ],
    verbs: [
      {
        cat: "tenses",
        s: "-ıyor / -iyor / -uyor / -üyor",
        m: "Настоящее продолженное",
        e: "Geliyorum (Я иду), Bakıyor (Смотрит)",
      },
      {
        cat: "tenses",
        s: "-di / -dı / -du / -dü",
        m: "Прошедшее категорическое (увиденное)",
        e: "Geldi (Он пришел)",
      },
      {
        cat: "tenses",
        s: "-miş / -mış / -muş / -müş",
        m: "Прошедшее субъективное (услышанное)",
        e: "Gelmiş (Говорят, он пришел)",
      },
      {
        cat: "tenses",
        s: "-ecek / -acak",
        m: "Будущее",
        e: "Gelecek (Он придет)",
      },
      {
        cat: "tenses",
        s: "-r / -er / -ar",
        m: "Aorist (Привычное / Вежливое)",
        e: "Gelir (Он обычно приходит)",
      },
      {
        cat: "person",
        s: "-im / -ım",
        m: "Личное окончание: Я",
        e: "Yazıyorum (Я пишу)",
      },
      {
        cat: "person",
        s: "-sin / -sın",
        m: "Личное окончание: Ты",
        e: "Yazıyorsun (Ты пишешь)",
      },
      {
        cat: "person",
        s: "ø",
        m: "Личное окончание: Он/Она",
        e: "Yazıyor (Он пишет)",
      },
    ],
    derivations: [
      {
        cat: "derivation",
        s: "-ci / -cı / -cü / -cu",
        m: "Профессия / Деятель",
        e: "Sütçü (Молочник)",
      },
      {
        cat: "derivation",
        s: "-lik / -lık / -lük / -luk",
        m: "Абстракция / Место хранения",
        e: "Güzellik (Красота), Kitaplık (Книжный шкаф)",
      },
      {
        cat: "derivation",
        s: "-li / -lı / -lü / -lu",
        m: "С чем-то / Обладание свойством",
        e: "Şekerli (С сахаром)",
      },
      {
        cat: "derivation",
        s: "-siz / -sız / -süz / -suz",
        m: "Без чего-то / Отсутствие",
        e: "Şekersiz (Без сахара)",
      },
    ],
  },
};

import type { ConstructorRoot, ConstructorSuffix } from "./types";

export const CONSTRUCTOR_ROOTS: ConstructorRoot[] = [
  { id: "noun-ev", root: "ev", pos: "NOUN", glossEn: "house", glossRu: "дом" },
  {
    id: "noun-kitap",
    root: "kitap",
    pos: "NOUN",
    glossEn: "book",
    glossRu: "книга",
  },
  {
    id: "noun-kadin",
    root: "kadın",
    pos: "NOUN",
    glossEn: "woman",
    glossRu: "женщина",
  },
  {
    id: "noun-araba",
    root: "araba",
    pos: "NOUN",
    glossEn: "car",
    glossRu: "машина",
  },
  {
    id: "noun-sehir",
    root: "şehir",
    pos: "NOUN",
    glossEn: "city",
    glossRu: "город",
  },
  {
    id: "noun-ogretmen",
    root: "öğretmen",
    pos: "NOUN",
    glossEn: "teacher",
    glossRu: "учитель",
  },
  {
    id: "verb-gel",
    root: "gel",
    pos: "VERB",
    glossEn: "come",
    glossRu: "приходить",
  },
  { id: "verb-git", root: "git", pos: "VERB", glossEn: "go", glossRu: "идти" },
  {
    id: "verb-yaz",
    root: "yaz",
    pos: "VERB",
    glossEn: "write",
    glossRu: "писать",
  },
  {
    id: "verb-oku",
    root: "oku",
    pos: "VERB",
    glossEn: "read",
    glossRu: "читать",
  },
  {
    id: "verb-gor",
    root: "gör",
    pos: "VERB",
    glossEn: "see",
    glossRu: "видеть",
  },
  {
    id: "verb-sev",
    root: "sev",
    pos: "VERB",
    glossEn: "love",
    glossRu: "любить",
  },
  {
    id: "verb-bekle",
    root: "bekle",
    pos: "VERB",
    glossEn: "wait",
    glossRu: "ждать",
  },
  {
    id: "adj-buyuk",
    root: "büyük",
    pos: "ADJ",
    glossEn: "big",
    glossRu: "большой",
  },
  {
    id: "adj-hizli",
    root: "hızlı",
    pos: "ADJ",
    glossEn: "fast",
    glossRu: "быстрый",
  },
  {
    id: "adj-guzel",
    root: "güzel",
    pos: "ADJ",
    glossEn: "beautiful",
    glossRu: "красивый",
  },
  {
    id: "adj-kucuk",
    root: "küçük",
    pos: "ADJ",
    glossEn: "small",
    glossRu: "маленький",
  },
  {
    id: "adj-mutlu",
    root: "mutlu",
    pos: "ADJ",
    glossEn: "happy",
    glossRu: "счастливый",
  },
  {
    id: "adj-sari",
    root: "sarı",
    pos: "ADJ",
    glossEn: "yellow",
    glossRu: "желтый",
  },
];

export const CONSTRUCTOR_SUFFIXES: ConstructorSuffix[] = [
  {
    id: "noun-plural",
    labelEn: "Plural",
    labelRu: "Мн. число",
    pattern: "lAr",
    category: "plural",
    pos: "NOUN",
    order: 10,
  },
  {
    id: "noun-poss-1sg",
    labelEn: "My",
    labelRu: "Мой",
    pattern: "Im",
    category: "possessive",
    pos: "NOUN",
    order: 20,
  },
  {
    id: "noun-poss-2sg",
    labelEn: "Your (sg)",
    labelRu: "Твой",
    pattern: "In",
    category: "possessive",
    pos: "NOUN",
    order: 20,
  },
  {
    id: "noun-poss-3sg",
    labelEn: "His/Her",
    labelRu: "Его/Её",
    pattern: "I",
    category: "possessive",
    pos: "NOUN",
    order: 20,
    buffer: "s",
  },
  {
    id: "noun-poss-1pl",
    labelEn: "Our",
    labelRu: "Наш",
    pattern: "ImIz",
    category: "possessive",
    pos: "NOUN",
    order: 20,
  },
  {
    id: "noun-poss-2pl",
    labelEn: "Your (pl)",
    labelRu: "Ваш",
    pattern: "InIz",
    category: "possessive",
    pos: "NOUN",
    order: 20,
  },
  {
    id: "noun-poss-3pl",
    labelEn: "Their",
    labelRu: "Их",
    pattern: "lArI",
    category: "possessive",
    pos: "NOUN",
    order: 20,
  },
  {
    id: "noun-accusative",
    labelEn: "Accusative",
    labelRu: "Винительный",
    pattern: "I",
    category: "cases",
    pos: "NOUN",
    order: 30,
    buffer: "y",
  },
  {
    id: "noun-dative",
    labelEn: "Dative",
    labelRu: "Дательный",
    pattern: "A",
    category: "cases",
    pos: "NOUN",
    order: 30,
    buffer: "y",
  },
  {
    id: "noun-locative",
    labelEn: "Locative",
    labelRu: "Местный",
    pattern: "DA",
    category: "cases",
    pos: "NOUN",
    order: 30,
  },
  {
    id: "noun-ablative",
    labelEn: "Ablative",
    labelRu: "Исходный",
    pattern: "DAn",
    category: "cases",
    pos: "NOUN",
    order: 30,
  },
  {
    id: "noun-genitive",
    labelEn: "Genitive",
    labelRu: "Родительный",
    pattern: "In",
    category: "cases",
    pos: "NOUN",
    order: 30,
    buffer: "n",
  },
  {
    id: "verb-pres-cont",
    labelEn: "Present continuous",
    labelRu: "Настоящее длительное",
    pattern: "Iyor",
    category: "tenses",
    pos: "VERB",
    order: 10,
    contract: "dropLastVowel",
  },
  {
    id: "verb-past",
    labelEn: "Past (seen)",
    labelRu: "Прош. (увид.)",
    pattern: "DI",
    category: "tenses",
    pos: "VERB",
    order: 10,
  },
  {
    id: "verb-reported",
    labelEn: "Past (reported)",
    labelRu: "Прош. (услыш.)",
    pattern: "mIş",
    category: "tenses",
    pos: "VERB",
    order: 10,
  },
  {
    id: "verb-future",
    labelEn: "Future",
    labelRu: "Будущее",
    pattern: "AcAk",
    category: "tenses",
    pos: "VERB",
    order: 10,
  },
  {
    id: "verb-aorist",
    labelEn: "Aorist",
    labelRu: "Аорист",
    pattern: "Ar",
    category: "tenses",
    pos: "VERB",
    order: 10,
    contract: "dropSuffixVowel",
  },
  {
    id: "verb-1sg",
    labelEn: "I",
    labelRu: "Я",
    pattern: "Im",
    category: "person",
    pos: "VERB",
    order: 20,
  },
  {
    id: "verb-2sg",
    labelEn: "You (sg)",
    labelRu: "Ты",
    pattern: "sIn",
    category: "person",
    pos: "VERB",
    order: 20,
  },
  {
    id: "verb-3sg",
    labelEn: "He/She/It",
    labelRu: "Он/Она",
    pattern: "",
    category: "person",
    pos: "VERB",
    order: 20,
  },
  {
    id: "verb-1pl",
    labelEn: "We",
    labelRu: "Мы",
    pattern: "Iz",
    category: "person",
    pos: "VERB",
    order: 20,
  },
  {
    id: "verb-2pl",
    labelEn: "You (pl)",
    labelRu: "Вы",
    pattern: "sInIz",
    category: "person",
    pos: "VERB",
    order: 20,
  },
  {
    id: "verb-3pl",
    labelEn: "They",
    labelRu: "Они",
    pattern: "lAr",
    category: "person",
    pos: "VERB",
    order: 20,
  },
  {
    id: "adj-with",
    labelEn: "With / having",
    labelRu: "С / обладающий",
    pattern: "lI",
    category: "derivation",
    pos: "ADJ",
    order: 10,
  },
  {
    id: "adj-without",
    labelEn: "Without / lacking",
    labelRu: "Без / лишенный",
    pattern: "sIz",
    category: "derivation",
    pos: "ADJ",
    order: 10,
  },
  {
    id: "adj-ness",
    labelEn: "Abstract noun (-ness)",
    labelRu: "Абстрактность (-ность)",
    pattern: "lIk",
    category: "derivation",
    pos: "ADJ",
    order: 10,
  },
];
